[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "^4.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true