CREATE TABLE events(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trace_id BINARY(16) NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  actor_id BINARY(16) NOT NULL,
  name TINYTEXT NOT NULL,
  version INT NOT NULL,
  data TEXT NOT NULL,
  created DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
)ENGINE=InnoDB;

CREATE TRIGGER events_upd BEFORE UPDATE ON events FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'UPDATE not allowed on events table';
END;

CREATE TRIGGER events_del BEFORE DELETE ON events FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'DELETE not allowed on events table';
END;