CREATE TABLE events(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_id BIGINT UNSIGNED NOT NULL,
  name TINYTEXT NOT NULL,
  version INT NOT NULL,
  data TEXT NOT NULL,
  created DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
)ENGINE=InnoDB;